// 365 curated daily conversation questions for couples
// Deterministic question selection: same couple + date → same question

const PLAYFUL_EMOJIS = ['🎲', '🌅', '🍳', '🎭']
const REFLECTIVE_EMOJIS = ['💭', '🌙', '🪞', '🌿']
const HYPOTHETICAL_EMOJIS = ['✨', '🌌', '🎪', '🌊']
const MEMORY_EMOJIS = ['💝', '🌸', '📸', '🎞️']
const OPINION_EMOJIS = ['💬', '🎯', '🧩', '📐']
const FUTURE_EMOJIS = ['🌟', '🌠', '🚀', '🌱']
const IMAGINATIVE_EMOJIS = ['🎭', '🌈', '🎨', '🎵']

function tag(arr, emojis) {
  return arr.map((text, i) => ({ text, emoji: emojis[i % emojis.length] }))
}

const PLAYFUL = tag([
  "What's your ideal Sunday morning look like?",
  "If you could eat only one cuisine for the rest of your life, what would it be?",
  "What's a TV show you're embarrassed to admit you love?",
  "Would you rather live somewhere always sunny or have all four seasons?",
  "What's the most random skill you have?",
  "If you had to pick one song to wake up to every day, what would it be?",
  "Morning person or night owl — and do you wish you were the other?",
  "What's your go-to comfort food when you're exhausted?",
  "You get an extra hour today. What do you do with it?",
  "What's a small, weird thing that makes you inexplicably happy?",
  "What's the last thing that made you laugh out loud?",
  "Coffee, tea, or something else — and how do you actually make it?",
  "What's a game you'd want to play together sometime?",
  "If you could teleport anywhere right now, where would you go?",
  "What's a completely harmless habit you have that others find odd?",
  "What does your ideal lazy day look like?",
  "What's the best snack you've discovered recently?",
  "If you had to pick a new hobby you've never tried, what would it be?",
  "What's a childhood Saturday morning you remember fondly?",
  "What's the most ambitious thing on your current to-do list?",
  "If you opened a café, what would it look like and what would be on the menu?",
  "What's a song that always puts you in a good mood?",
  "If you could have a superpower just for everyday convenience, what would it be?",
  "What's your guilty pleasure movie or show?",
  "What's something you'd splurge on without hesitation?",
  "Name one place near you that you've never visited but always meant to.",
  "What's the best meal you've cooked for yourself?",
  "What's a word in your language you think sounds beautiful?",
  "If you could add one room to your home, what would it be for?",
  "What's a style or aesthetic you secretly love but don't fully embrace?",
  "If you had to pick a different name for yourself, what would you choose?",
  "What's a small, free thing that genuinely makes a day better?",
  "What's the perfect weekend weather to you?",
  "What's a local spot — restaurant, park, café — you think is underrated?",
  "If you were a dog breed, which one fits you best and why?",
  "What's something you always buy the fancy version of?",
  "What's a simple pleasure you'd never give up?",
  "What's a food combination that sounds weird but you love?",
  "If you could only read one book genre for a year, what would it be?",
  "What's a trend everyone seems to love but you find overrated?",
  "What's the funniest thing you've seen this week?",
  "If you could instantly master one physical skill, what would it be?",
  "What's the best nap you've ever taken?",
  "If you had to describe your style in three words, what would they be?",
  "What's the best meal you've had at someone else's home?",
  "What's a store where you always spend more than you planned?",
  "If you could swap lives with a fictional character for a day, who would it be?",
  "What's a phrase or word you use too much?",
  "What's a small design detail — in a product, room, or app — you genuinely appreciate?",
  "What's the most comfortable piece of clothing you own?",
  "What's a type of day you wish you had more of?",
  "What's something that feels like a treat even when it's ordinary?",
], PLAYFUL_EMOJIS)

const REFLECTIVE = tag([
  "What's something you've changed your mind about in the last year?",
  "What's a skill you're proud of that most people don't know you have?",
  "When do you feel most like yourself?",
  "What's something you're quietly working on improving?",
  "What's a mistake you've made that you're genuinely grateful happened?",
  "What's a compliment that stuck with you for a long time?",
  "What's the last thing you read or watched that genuinely shifted your perspective?",
  "What's a belief you hold that you find hard to explain to others?",
  "What's something you used to be embarrassed about that you've made peace with?",
  "What's your relationship with being alone like?",
  "What does 'home' mean to you beyond a physical place?",
  "What's a recurring worry that you're learning to quiet?",
  "When do you feel most creative?",
  "What's a part of your personality that took you longest to appreciate?",
  "What's something that takes real courage for you, even if it looks easy to others?",
  "What does a genuinely good day feel like for you?",
  "What's something you do that you'd consider a form of self-care, even if it sounds strange?",
  "What's a goal you've quietly had for years but haven't told many people?",
  "What's something you wish you'd learned earlier in life?",
  "What's a pattern in yourself you're trying to break?",
  "What does success mean to you right now — not long-term, just this year?",
  "What's a fear you've gotten better at facing?",
  "How do you recharge after a draining week?",
  "What's something that bothers you in the moment but you tend to forget quickly?",
  "What's a standard you hold yourself to that you don't hold others to?",
  "What's something you do alone that feels almost meditative?",
  "What's a piece of advice you keep coming back to?",
  "What does loyalty mean to you in practice?",
  "What's something in your life you're trying to simplify?",
  "What's a value you realized you had only after it was tested?",
  "When do you feel most understood by someone?",
  "What's a version of yourself from a few years ago that you look back on fondly?",
  "What's something you find deeply satisfying that other people might find boring?",
  "What's a conversation topic that makes you come alive?",
  "What does growing up mean to you — is it a good thing?",
  "What's a way you've surprised yourself recently?",
  "What's something about your childhood that still shows up in how you are today?",
  "What would 'enough' look like for you — when would you feel like you have what you need?",
  "What's something you do out of habit that you want to do more intentionally?",
  "What's a moment in the last year where you were proud of how you handled something?",
  "What do you think is the most misunderstood thing about you?",
  "What's a tension you hold — two things you believe that seem to contradict each other?",
  "What's something you're still figuring out about yourself?",
  "What's an emotion that visits you often but you rarely name out loud?",
  "What's the last thing that felt genuinely difficult and how did you get through it?",
  "What's something that used to take effort that now comes naturally?",
  "What's a relationship dynamic you've actively worked on improving?",
  "What's something you've had to forgive yourself for?",
  "What's a small ritual you rely on more than you'd admit?",
  "What's a word that describes where you are in life right now?",
  "What's a truth about yourself you had to accept that you initially resisted?",
  "What's something you do that you think is unique to you?",
  "What's a lesson life has taught you that you couldn't learn from a book?",
  "What's something that makes you feel genuinely generous?",
  "What does being brave look like for you in everyday life?",
], REFLECTIVE_EMOJIS)

const HYPOTHETICAL = tag([
  "If you could have dinner with any person, living or historical, who and where?",
  "If you had unlimited budget but only one week, what would your perfect trip look like?",
  "If you had to live in a different country for five years, where would you go?",
  "If you could instantly speak any language fluently, which one?",
  "If you found out you had one month of total freedom — no obligations — what would you do?",
  "If you could go back and give your 15-year-old self one piece of advice, what would it be?",
  "If you had to switch careers completely, what would you do?",
  "If you could live in any era of history, which would you choose?",
  "If you had to write a book, what would it be about?",
  "If we had to choose between city life and rural life forever, which would you pick and why?",
  "If you could only watch films from one decade for the rest of your life, which?",
  "If you could ask anyone in the world one honest question and get an honest answer, who and what?",
  "If you had to design your ideal workspace, what would it look like?",
  "If you could take a gap year starting tomorrow, how would you spend it?",
  "If you had to pick one thing to get really good at in the next five years, what would it be?",
  "If you could live somewhere with a completely different climate than you do now, what would you pick?",
  "If money were no issue, what's the first thing you'd change about where you live?",
  "If you had to move to a city you've never lived in, where would you go?",
  "If you could only own 100 physical things total, what would you keep?",
  "If you had to give a TED talk tomorrow, what would your topic be?",
  "If you could change one thing about how the world works, what would it be?",
  "If you had a time machine but could only observe, not intervene, what era would you visit?",
  "If you had to simplify your life drastically — smaller home, fewer possessions — how would that go?",
  "If you could master one creative skill instantly — painting, music, writing, cooking — which?",
  "If you had to describe this stage of your life as a movie genre, what would it be?",
  "If you could redesign one thing about modern life from scratch, what would it be?",
  "If you could send a letter to yourself 10 years from now, what's the one thing you'd want to know?",
  "If you had to teach a class on something you genuinely know well, what would you teach?",
  "If you could experience a different profession for just one day, which one and why?",
  "If we had to design our perfect home together from scratch, where would it be and what would it have?",
  "If you could pick one technology to be un-invented, what would it be?",
  "If you could bring one extinct animal back, which one?",
  "If you could learn the complete truth about one unsolved mystery, which one?",
  "If you had to live with no internet for a year — everything else the same — how would life change?",
  "If you could have any view from your window, what would it be?",
  "If you could only celebrate one holiday for the rest of your life, which one?",
  "If you had to write a motto for how you try to live, what would it be?",
  "If you could fix one thing about yourself overnight (not appearance), what would it be?",
  "If you had to pick one skill or trait to pass on to a future generation, what would it be?",
  "If we could only do one thing together on weekends for the rest of our lives, what would you pick?",
  "If you had to trade places with any animal for a day, which one?",
  "If you could attend any event in history as a spectator, what would you choose?",
  "If you could abolish one social norm, which one?",
  "If you had to describe your ideal life in five years in one paragraph, what would it say?",
  "If you could make one thing free for everyone in the world, what would it be?",
  "If you had to redesign one day of the week, which would it be and how?",
  "If you could go back to any age for just one day, what age and why?",
  "If you had to pick a side career that has nothing to do with your actual work, what would it be?",
  "If you could erase one awkward memory, would you?",
  "If you could only use one app for the rest of your life, which one?",
], HYPOTHETICAL_EMOJIS)

const MEMORY = tag([
  "What's the first thing about me that made you curious?",
  "What's a moment from our relationship that you think about more than I'd expect?",
  "What's something I do that you've secretly started doing yourself?",
  "What's a trip or day with me that felt ordinary but that you look back on fondly?",
  "What's something I've said to you that stayed with you longer than I probably know?",
  "What's a small thing I do that you find genuinely sweet?",
  "When did you first feel like we were actually us — a real unit?",
  "What's a habit of mine you've silently adjusted to?",
  "What's something about our relationship that surprised you compared to how you imagined it?",
  "What's a version of me you haven't fully met yet that you're curious about?",
  "What's something you're better at because of me?",
  "What's a moment you felt truly taken care of by me?",
  "What's an inside joke or reference that only we'd understand?",
  "What's something you want more of in the way we communicate?",
  "What's a memory from when we first met that you haven't told me?",
  "What's something you've learned about yourself from being with me?",
  "What's a place that now has a specific memory of us attached to it?",
  "What's a time I surprised you in a good way?",
  "What's something you didn't expect to love about our dynamic?",
  "What's a worry you had early on that turned out to be nothing?",
  "What's something I misunderstand about you that you want to explain?",
  "What do you think our biggest strength as a pair is?",
  "What's something we haven't done together yet that you really want to?",
  "What's a word you'd use to describe how I make you feel when things are hard?",
  "What's a thing I say or do that makes you feel immediately at ease?",
  "What's something about your daily life that you wish I could see firsthand?",
  "What's a moment where you thought 'this is the person for me' and didn't say it out loud?",
  "What's something you want us to be better about together?",
  "What's a tradition — even a small one — that you love having with me?",
  "What's something you've never told me but always wanted to?",
  "What's the clearest image of a perfect day with me that you can picture?",
  "What's something I do that makes you feel loved in a way you don't always articulate?",
  "What's a version of our future you think about most?",
  "What's something small about our relationship that you're quietly proud of?",
  "What's something we've been through that made us stronger without being dramatic about it?",
  "What's a thing you wish I asked you about more?",
  "What's something about my life before us that you think shaped me in a way you see now?",
  "What's a moment you felt close to me despite the distance?",
  "What's one thing we're both bad at that we should just accept?",
  "What's a trait of mine you didn't notice until you'd known me for a while?",
  "What's a time I made you feel genuinely understood?",
  "What's a way our relationship has changed you that you wouldn't have predicted?",
  "What's something you believe about us that you don't say enough?",
  "What's a hard conversation we had that you're glad we had?",
  "What's something you secretly brag about when you talk about me to others?",
  "What's a ritual you want us to still have in ten years?",
  "What's a small moment from our relationship that represents us perfectly?",
  "What's something you want me to know about how I've shown up for you?",
  "What's a question you've always wanted to ask me but kept stopping yourself?",
  "What's something about being with me that you find unexpectedly easy?",
  "What's the most honest thing you can say about loving someone across distance?",
  "What's a way you need me to show up for you that you haven't fully said yet?",
  "What's a small moment of kindness between us that you still think about?",
  "What's something about our relationship you'd want others to see if they asked what love looks like?",
  "What's a specific phrase I could say to you that would instantly make a hard moment better?",
  "What's something I've done for you that you don't think I know mattered?",
  "What's a version of us in the future that you think about and smile?",
  "What's a difference between us that you've come to appreciate rather than find frustrating?",
  "What's something you've given up for this relationship that you don't regret?",
  "What's something about this phase of us that you want to remember?",
], MEMORY_EMOJIS)

const OPINION = tag([
  "What's something everyone seems to agree on that you quietly disagree with?",
  "What's an unpopular opinion you hold fairly confidently?",
  "What do you think is the most underrated life skill?",
  "What's an experience you think everyone should have at least once?",
  "What's something that's considered 'basic' that you genuinely love unironically?",
  "What's a type of person you find genuinely difficult to understand?",
  "What's the most important thing in a friendship?",
  "What's a tradeoff in life that you think people get wrong?",
  "What do you think is underrated about getting older?",
  "What's something you think people care too much about?",
  "What makes a city feel like home to you?",
  "What do you think is the best way to meet people as an adult?",
  "What's a social ritual you find more meaningful than people realize?",
  "What's changed about how you measure a good day?",
  "What's an area of life where simplicity beats complexity?",
  "What do you think is the biggest thing people get wrong about introversion or extroversion?",
  "What's the best gift you can give someone — not buying, but doing?",
  "What do you think makes a meal truly memorable?",
  "What's something people tend to rush that you think deserves more time?",
  "What's a small luxury that's worth every bit of the cost?",
  "What's your honest relationship with social media?",
  "What's a quality that you think is underrated in a romantic partner?",
  "What's the most important thing you can give someone going through a hard time?",
  "What's a piece of conventional wisdom you think is wrong?",
  "What's something people spend too little money on?",
  "What's something people spend too much time worrying about?",
  "What's something that's gotten harder as you've gotten older that you didn't expect?",
  "What do you think makes someone genuinely interesting to talk to?",
  "What do you think is the most overrated form of self-improvement?",
  "What's a cultural thing about where you grew up that other places could learn from?",
  "What's an opinion about food you'd defend strongly?",
  "What's something about the internet that you think has been genuinely good for people?",
  "What's something about your personality that you think is misread as a flaw?",
  "What's a question you think more people should ask themselves?",
  "What do you think is the difference between a good day and a great one?",
  "What's an expectation society has that you think is worth questioning?",
  "What do you think is the most honest test of someone's character?",
  "What's something you've changed your mind about regarding relationships?",
  "What's a social rule you think should exist but doesn't?",
  "What do you think is the best use of a Saturday with no obligations?",
  "What's something about ambition that you think is misunderstood?",
  "What's something you think is genuinely harder for your generation than for previous ones?",
  "What do you think is the most important thing to have in common with a partner?",
  "What's something about 'adulting' that you've actually started to like?",
  "What's a form of entertainment you think is underappreciated?",
  "What do you think is the real point of taking a vacation?",
  "What's a habit people have that you find genuinely impressive?",
  "What's something about how people communicate today that you'd change?",
  "What's a question you think every couple should ask each other?",
  "What do you think is the most honest thing you can say about being happy?",
  "What's an assumption people make about your life that's completely wrong?",
  "What's something about how you were raised that you'd keep for your own life?",
  "What do you think separates enjoying life from just getting through it?",
  "What's a quality in people that you think is rarer than it should be?",
  "What's something you find genuinely overrated that most people love?",
], OPINION_EMOJIS)

const FUTURE = tag([
  "In five years, what do you hope looks completely different about your life?",
  "What's a dream you have that you rarely say out loud?",
  "What kind of old person do you want to be?",
  "What does a really good year look like for you from the inside?",
  "What's something you want to accomplish that you'd be embarrassed if you never tried?",
  "What's a version of your life in ten years that you'd feel proud of?",
  "What's something you want to learn or become that has nothing to do with your career?",
  "What does the home you want to eventually live in look like?",
  "If we're still together in twenty years, what do you hope we're still doing together?",
  "What's a place you want to visit before you feel like you've really seen the world?",
  "What's something about the future that genuinely excites you?",
  "What does 'having made it' look like to you — and is that still what you want?",
  "What's a legacy you want to leave — small or large?",
  "What's something you want to do that would scare you to try?",
  "What kind of community do you want to be part of eventually?",
  "What's one thing you'd want your future self to say about how you lived this decade?",
  "What's a relationship you want to invest more in going forward?",
  "What does financial security mean to you concretely, not abstractly?",
  "What's a creative project you'd love to have completed someday?",
  "What's something you hope you never stop doing, no matter how old you get?",
  "What's a rhythm of life — routines, pace, priorities — you want to build toward?",
  "What's a fear about the future that you're choosing to face anyway?",
  "What does a good later-in-life look like to you — not the finances, the actual days?",
  "What's a habit you want to build now that your future self will thank you for?",
  "If we built something together — a project, a business, a home — what would it look like?",
  "What's a version of your career in ten years that would feel meaningful?",
  "What's a place you could imagine spending a whole year and never getting bored?",
  "What's something you're willing to wait a long time for because it'll be worth it?",
  "What's a tradition you want to start this year?",
  "What's a skill you want to teach someone someday?",
  "What's a version of your everyday life five years from now that feels both realistic and wonderful?",
  "What's something about getting older that you're genuinely looking forward to?",
  "What does 'enough' look like in a life well-lived to you?",
  "What's a chapter of your life you're excited to eventually get to?",
  "What's a goal that terrifies you because it actually matters to you?",
  "What's one thing you'd tell your future self never to forget about right now?",
  "What's something you want to build into your life that you don't currently have room for?",
  "If you could design the rest of this year, what would the highlight be?",
  "What's a version of us in the future that feels like the truest version of who we are?",
  "What's something you're quietly optimistic about?",
  "What's something you want to be known for eventually?",
  "What does an ideal morning look like five years from now?",
  "What's something you want to figure out before you hit the next decade?",
  "What's something small you can start now that leads somewhere meaningful?",
  "What's a city or country you could imagine calling home someday?",
  "What's something you want to do that would make the best version of yourself proud?",
  "What's a lesson you hope to learn in the next year?",
  "What does the version of you that's thriving look like day-to-day?",
  "What's something you want to give more of — time, attention, love — in the years ahead?",
  "What's a version of your life that you'd find quietly, completely satisfying?",
], FUTURE_EMOJIS)

const IMAGINATIVE = tag([
  "If your current life were a film, what genre is it and who'd direct it?",
  "If you had to describe today's mood as a weather pattern, what would it be?",
  "If your life had a soundtrack right now, what's the opening track?",
  "If you had to pick a color that represents this chapter of your life, what would it be and why?",
  "If someone was trying to understand you and could only read one book, what would it be?",
  "If your personality were a city, which city would it be?",
  "If you had to describe your ideal life as a scene in a movie, what's happening in that scene?",
  "If you were a season, which one and why?",
  "If your inner world were a physical place — landscape, weather, architecture — what would it look like?",
  "If you had to describe our relationship as a recipe, what are the ingredients?",
  "If you could only express yourself in one creative medium, which one?",
  "If your current state of mind were a room, what would it look like?",
  "If your life were a book, what would this chapter be called?",
  "If you could give this year a one-word title, what would it be?",
  "If you had to design a flag for yourself, what would be on it?",
  "If your ideal self were a character in a story, what kind of story would they live in?",
  "If you had to design a playlist for this phase of your life, what's the first song?",
  "If you were an element — fire, water, air, earth — which one right now?",
  "If your personality had a texture, what would it be?",
  "If you could describe this year as a smell, what would it be?",
  "If you had to describe where you are in life as a time of day, what time is it?",
  "If you could create a holiday for something you value, what would it celebrate?",
  "If your love language were a landscape, what would it look like?",
  "If you had to write a poem about today in three lines, what would they be?",
  "If your current self met the version of you from three years ago, what would surprise each of you?",
  "If you had to capture this moment of your life in a single photograph, what would it show?",
  "If our relationship had a mascot, what would it be?",
  "If you had to name a constellation after something you love, what would you name it?",
  "If your life were an exhibition — like an art show — what's the central piece?",
  "If you had to put three objects in a time capsule that represent you right now, what would they be?",
  "If you had to describe yourself as a type of light — candlelight, sunlight, neon, starlight — which?",
  "If your biggest dream had a shape, what would it be?",
  "If your emotional life this year were a painting, what does it look like?",
  "If the story of us were a song, what kind of song is it?",
  "If you could take a photo of a feeling you've had recently, what feeling and how would you capture it?",
  "If this conversation were a room, what would it look like?",
  "If you had to describe love as a sound, what sound would it be?",
  "If you could bottle one feeling from this year, what would it be?",
  "If you had to describe your current energy as a natural phenomenon — storm, sunrise, fog — what is it?",
  "If your current life were a chapter in a longer story, what came before and what do you hope comes next?",
  "If you could make today last longer, which part of it?",
  "If you had to design a coat of arms for your family, what symbols would be on it?",
  "If you had to describe the feeling of being loved by someone as a place, what place?",
], IMAGINATIVE_EMOJIS)

export const DAILY_QUESTIONS = [
  ...PLAYFUL,
  ...REFLECTIVE,
  ...HYPOTHETICAL,
  ...MEMORY,
  ...OPINION,
  ...FUTURE,
  ...IMAGINATIVE,
]

// Deterministic hash: same coupleId + date always returns the same question
// Both partners resolve identical questions without coordination
function hashStr(s) {
  let h = 0
  for (let i = 0; i < s.length; i++) {
    h = (Math.imul(31, h) + s.charCodeAt(i)) | 0
  }
  return Math.abs(h)
}

export function pickQuestion(coupleId, date) {
  const idx = hashStr(coupleId + date) % DAILY_QUESTIONS.length
  return DAILY_QUESTIONS[idx]
}
